debridge-finance/dln-taker

- src/providers/evm.provider.adapter.ts
This PR relaxes order unlocking: instead of waiting for `sendUnlock()` txn being including to the block, it waits only for node accept the transaction for further broadcast, which is enough because in case txn is being lost, it can be generated again (funds are still safu).
> Improvement: sendUnlock() on EVM chains must not wait txns' confirmations

- package-lock.json
- package.json
- src/index.ts
This PR forces BigNumber to almost never using the scientific notation while casting amounts to string.
The default exponentiation threshold of 20 decimals causes thousands of tokens with decimals 18+ to be converted to string using scientific notation, which is not properly parsed by `bigint`
> feat: BigNumber now never uses scientific notation when converting to string

- package-lock.json
- package.json
- src/processors/universal.ts
During order estimation, the dln-taker has been picking the bucket using recommendation algorithm, which is used upon order creation and is allowed to pick arbitrary bucket regardless of give token. This caused some orders to stuck because picket bucket's selected token was not the same as order's give token: for example, for the order `0x831fc3ddc5b96eb1717a110bee45a2f4d71f6dcfc4e0b623305e286ecebfbef4` (USDC -> ETH) the ETH bucket was chosen, though the USDC bucket has been expected to be picked. 
This PR switches dln-taker to use another algorithm of bucket selection, which is suitable for order estimation.
Only dln-ts-client v3.6.2 exposes this algorithm.
> fix: incorrect bucket selection

- package-lock.json
- package.json
This PR updates dln-ts-client to v3.6.3, where order estimation algorithm slightly changed and uses only half of the calculated slippage during order profitability estimation.
No BC breaks.
> feat: update dln-ts-client to v3.6.3 with half slippage

- package-lock.json
- package.json
This PR updates dln-ts-client to https://github.com/debridge-finance/dln-ts-client/releases/tag/v4.0.3, which allows disabling PMM protocols when querying swap txns from 1inch
Task-id: DEV-2616
> chore: update dln-ts-client to 4.0.3 (disable PMMs from 1inch)

- package-lock.json
- package.json
- src/executors/executor.ts
- src/processors/BatchUnlocker.ts
- src/processors/universal.ts
This PR updates dln-client to https://github.com/debridge-finance/dln-ts-client/releases/tag/v4.0.5.
With this update:
- slippage buffer is not reserved upon estimating pre-fulfill swap from the `reserveToken` to `takeToken`, relying on the given outcome
- minAmount for pre-fulfill swap is calculated as a ratio between estimated outcome (`evaluatedTakeAmount`) and the requested `takeAmount`, but not less than 5bps or more than 3bps
- pre-fulfill swap refund are sent to the taker's address
Task ID: DEV-2684
> feat: disable slippage buffer reservation when estimating pre-fullfil swap

- README.md
- package-lock.json
- package.json
- src/config.ts
- src/executors/executor.ts
- src/processors/universal.ts
This PR introduces new `dstConstraints.preFulfillSwapChangeRecipient` property which is able to set where the change of a possible pre-fulfill swap should be transferred to. Possible values:
- `maker`: the change would be transferred to maker defined as orders' `orderAuthorityDstAddress`
- `taker`: the change would be transferred back to the taker
> feature: pre-fulfill swap's change recipient

- package-lock.json
- package.json
This PR updates dln-ts-client to v5.5.0. This is a maintenance upgrade, needed to get rid of deprecated price impact detection algorithm which used undocumented price feeds.
> chore: dln-ts-client up v5.5.0

- package-lock.json
- package.json
- sample.config.ts
- src/config.ts
- src/configurator/tokenPriceService.ts
- src/hooks/HookEnums.ts
- src/processors/universal.ts
This PR introduces a small fix that prevents the script from attempting to estimate orders that require pre-fulfill swaps where such swaps are not yet available (e.g., on Linea or Base). 
This PR also adds `USDC` to the list of sample buckets
> fix: reject orders that require pre-fulfill swaps where swaps are not available

- package-lock.json
- package.json
- src/executors/executor.ts
This PR fixes a bug in address initialization picker: custom predefined addresses were not respected during chain initialization, which may lead to using default addresses instead. This caused Optimism chain to use default `CrosschainForwarder` address instead of custom one.
> fix: evm address initialization didn't use predefined overrides

- README.md
- package-lock.json
- package.json
- src/processors/TVLBudgetController.ts
This PR fixes a small bug introduced by #92 were `unlock_authority` account (intended to initiate unlocking procedures to the given chain) has been erroneously used as `unlock_beneficiary` (intended to receive funds from the orders being successfully unlocked).
https://app.clickup.com/t/4717986/DEV-2892
> fix: TVLBudget may have been overestimated

- package-lock.json
- package.json
- src/processors/universal.ts
This PR fixes a bug that may cause non-finalized orders coming from Solana to be not seen by the executor. This bug was caused by #93 
Task ID: https://app.clickup.com/t/862kank6w
> fix: use lowered block confirmations when checking order status from Solana

- package-lock.json
- package.json
- src/executors/executor.ts
This PR fixes bug introduced in #113, that is causing processor configured in the config.ts (incl. custom profitability and batch size) to be ignored
Task ID: https://app.clickup.com/t/862kcg4hk
> fix: processor configured from config has been ignored

- package-lock.json
- package.json
- src/processors/universal.ts
This PR multiplies EVM txn gas by 1.05 to reduce chances of being out of gas (which is often a case in Avalanche C-chain). Multiplication is done in cost of reduced gasPrice multiplier
> feat: multiply evm tx gas

- package-lock.json
- package.json
* make expenses as 0 for order with take chain optimism in case when expenses less then 5%
Task: https://app.clickup.com/t/4717986/DEV-3833
> fix: make expenses as 0 when value less than 5%

- package-lock.json
- package.json
This update reflects a new requirement: https://github.com/debridge-finance/legacy-dln-profitability/pull/16
Follows #148
> update legacy-dln-profitability to reflect OP Horizon constraints

- package-lock.json
- package.json
This PR updates dln-ts-client to fix case when `jupiterConfig.blacklistedDexes` is not set and requests to jup.ag API are failing
> Update dln ts client v8.3.1

- package-lock.json
- package.json
- sample.config.ts
- src/chain-common/order-estimator.ts
- src/config.ts
- src/executor.ts
- src/index.ts
* allowSubsidy, subsidizationRules in config
When allowSubsidy is enabled, the module searches for the first suitable subsidy for the order, considering chain compatibility and values, then applies the found subsidy to reserveDstAmount if an appropriate range for USD_VALUE(order.give.amount) is identified.
Task: https://app.clickup.com/t/4717986/DEV-3968
See also: https://github.com/debridge-finance/legacy-dln-profitability/pull/22
> feature: order subsidization

- package-lock.json
- package.json
- src/processor.ts
Sometimes WS pushes orders in `ArchivalCreated` status which undesirably override the schedule of live orders received earlier. This PR fixes this behaviour by effectively ignoring archival orders if corresponding live orders are already known by the taker instance.
TaskID: https://app.clickup.com/t/4717986/DEV-4164
> fix: ignore accidental archival orders is corresponding  live orders are received

- package-lock.json
- package.json
- src/chain-common/order-validator.ts
- src/hooks/HookEnums.ts
This PR makes orders missing in the give-chain to be postponed instead of being rejected, because the RPC may have a lag that causes taker not to see the order being placed.
Task ID: https://app.clickup.com/t/4717986/DEV-4140
> feat: postpone orders missing in the give-chain rather then reject them

- package-lock.json
- package.json
- src/chain-common/order-validator.ts
>we need to move existence check to the end of algo in Taker as well, so that this check is performed right before broadcasting. Since we request Confirmed level from Websocket, let’s used processed for existence check too
Task ID: https://app.clickup.com/t/8693dgrdm
> feat: Improve Order check reliability

- package-lock.json
- package.json
- sample.config.ts
https://app.clickup.com/t/4717986/DEV-4514
Taker now takes OP Stack L1 fees into consideration when estimating order profitability
Test report could be found here: https://github.com/debridge-finance/cross-chain-api/pull/328
> feat: lay in OP Stack L1 fees
