src/executors/executor.ts
src/orderFeeds/ws.order.feed.ts

Reverts debridge-finance/dln-executor#39

Revert "Support ws reconnection"

---

src/processors/utils/approve.ts

Fix error when start app with TokensBucket 0x0000000000000000000000000000000000000000

avoid to approve native token

---

README.md

This PR sets proper link to the DLN app

fix: link to dln app

---

src/providers/evm.provider.adapter.ts

This PR reconsiders how rebroadcasting is handled by EVM adapter:
- whenever rebroadcast estimation fails, the transaction is considered failed (BUG)
- whenever rebroadcast failed, the transaction is considered failed (no need to wait unit poller reaches timeout)
- logging is streamlined
Version bump: v1.0.1

feat: EVM adapter rebroadcasting improved and streamlined; version bump: v1.0.1

---

README.md
docs/Solana-key-management.md

Describe how to generate keypair for solana

docs: add solana kp generation docs

---

README.md
package-lock.json
package.json

This PR bumps the version to v1.0.0

chore: version bump 1.0.0

---

src/executors/executor.engine.ts

feature: date in logs
fix: no colors when stdout in file

improve logging

---

README.md

chore: release 2.0.0

---

src/providers/evm.provider.adapter.ts
src/providers/utils/getEvmAccountBalance.ts

Due to a bug introduced by #36, retrieval of balance of ether was causing unexpected error. This PR fixes retrieval of balance of the native currency in EVM chains.

fix: retrieval of balance of the native currency in EVM

---

src/processors/universal.ts
src/providers/evm.provider.adapter.ts

This PR fixes a fatal bug which lead to empty txns being broadcasted instead of proper txns

fix: tx bypassed incorrectly

---

src/providers/evm.provider.adapter.ts

* round gas while rebroadcast
* change log level of sending transaction log

fix: round gas while rebroadcast

---

package-lock.json
package.json
src/processors/universal.ts

build: up @debridge-finance/dln-client to 3.5.0

build: up @debridge-finance/dln-client to 3.5.0

---

README.md
debridge.config.ts
sample.config.ts

This PR adds wETH token addresses from the Avalanche, BNB and Polygon chains to the ETH bucket.

feat: add wETH tokens on Avalanche, BNB and Polygon chains to the ETH bucket

---

README.md
debridge.config.ts
package-lock.json
package.json
sample.config.ts

This PR bumps version to v2.1.0

chore: release 2.1.0

---

package-lock.json
package.json
src/processors/universal.ts

Fixes:
* coingecko service worked incorrect with native token
* taker executed preswapAndFullfilll without parameters

fix: coingecko native address price and solana fullfil

---

src/hooks/handlers/OrderPostponedHookHandler.ts
src/hooks/handlers/OrderRejectedHookHandler.ts

* Remove the following notifications from the bot to avoid spam:
ALREADY_FULFILLED_OR_CANCELLED
NOT_ENOUGH_BLOCK_CONFIRMATIONS_FOR_ORDER_WORTH
* Replace dln.debridge.finance/ to app.debridge.finance/ in order link
Task links: 
https://app.clickup.com/t/4717986/DEV-2940
https://app.clickup.com/t/4717986/DEV-2921

filter some rejects notification and order link

---

README.md
package-lock.json
package.json
src/config.ts
src/executors/executor.ts
src/hooks/HookEnums.ts
src/interfaces.ts
src/processors/base.ts
src/processors/mempool.service.ts
src/processors/universal.ts

This PR introduces an opt-int feature to configure delayed fulfillments. More on this: https://github.com/debridge-finance/dln-taker/tree/feat-delayed-order-fulfillment#delayed-fulfillments
Task ID: https://app.clickup.com/t/4717986/DEV-3003

feat: delayed fulfillments

---

package-lock.json
package.json
src/processors/universal.ts

This PR fixes issue with retrieving the status of a non-finalized order coming from Solana

feat: correctly check order status for non-finalized orders coming from Solana

---

debridge.config.ts
sample.config.ts

* update configs with usdc bucket in base

feature: usdc bucket in base

---

package-lock.json
package.json
src/configurator/tokenPriceService.ts

This PR properly adds USDbC@Base as an intermediary token, extending #104

feat: properly add USDbC@Base

---

debridge.config.ts
package-lock.json
package.json
sample.config.ts
src/config.ts
src/environments.ts
src/executors/executor.ts
src/filters/give.amount.usd.equivalent.between.ts
src/filters/take.amount.usd.equivalent.between.ts
src/interfaces.ts
src/orderFeeds/ws.order.feed.ts
src/processors/BatchUnlocker.ts
src/processors/base.ts
src/processors/universal.ts
src/providers/evm.provider.adapter.ts
src/providers/provider.adapter.ts
src/providers/solana.provider.adapter.ts

This PR upgrades a principal dependency [@debridge-finance/dln-client](https://www.npmjs.com/package/@debridge-finance/dln-client) to a dramatically improved and refactored version 6.
This upgrade also enables batched unlocks (`send_batch_unlock`) to/from Solana.
Task ID: DEV-2929

feat: dln-ts-client upgraded to v6 with send_batch_unlock to/from Solana

---

README.md
package-lock.json
package.json
sample.config.ts
src/configurator/tokenPriceService.ts

This PR upgrades dln-ts-client to support proper token feeds from Coingecko

feat: add optimism native intermediary (ETH)

---

package-lock.json
package.json
src/processors/BatchUnlocker.ts
src/processors/universal.ts

This PR enables `batch_unlock`s for orders coming to/from Solana
Task ID: https://app.clickup.com/t/862kax929

feat: enable `batch_unlock`s to/from Solana

---

package-lock.json
package.json
src/config.ts
src/executors/executor.ts
src/processors/universal.ts
src/providers/evm.provider.adapter.ts
src/providers/provider.adapter.ts
src/providers/solana.provider.adapter.ts

This PR introduces EIP-1559 usage for chains where it is being supported.
Additionally, gas fee policy has been revised to use optimized constraints with well balanced speed and economy
Task: https://app.clickup.com/t/4717986/DEV-3431

feat: EIP-1559 support

---

package-lock.json
package.json
src/providers/evm.provider.adapter.ts

This fixes a bug introduced in #116: poller may have quit leaving the lock unreleased

fix: poller may have ended without releasing the lock

---

package-lock.json
package.json
src/config.ts
src/environments.ts
src/executors/executor.ts
src/helpers.ts
src/hooks/HookEnums.ts
src/orderFeeds/ws.order.feed.ts
src/processors/TVLBudgetController.ts
src/processors/base.ts
src/processors/universal.ts
src/providers/evm.provider.adapter.ts
src/providers/provider.adapter.ts
src/providers/solana.provider.adapter.ts
tsconfig.json

Task: https://app.clickup.com/t/4717986/DEV-3425

feat: dln-extcall

---

package-lock.json
package.json
src/providers/evm.provider.adapter.ts

https://app.clickup.com/t/862kd01gu

fix: set BNB gasPrice to be between 3gwei and 5gwei

---

src/errors.ts
src/interfaces.ts
src/processors/mempool.service.ts
src/processors/universal.ts

Task ID: https://app.clickup.com/t/862kd3m9u
This PR fixes a possible race condition when data stored internally is accessed after being truncated by another context

fix: avoid race condition when accessing order store

---

package-lock.json
package.json
src/processors/mempool.service.ts
src/processors/universal.ts

This PR slightly improves how mempool service works: live orders must be reprocessed more frequently, archival orders - less frequently
https://app.clickup.com/t/862kd44gy

feat: mempool uses separate delay configurations across live and archival orders

---

package-lock.json
package.json

Task: https://app.clickup.com/t/4717986/DEV-3577

fix: bignumber issue

---

package-lock.json
package.json
src/config.ts

* support base pre swap in dln
Task link: https://app.clickup.com/t/4717986/DEV-3600

feature: oneinch for base

---

package-lock.json
package.json
src/executors/executor.ts
src/processors/base.ts
src/processors/universal.ts

Task: https://app.clickup.com/t/4717986/DEV-3611

fix: events from WS now handled sequentially

---

package-lock.json
package.json
src/hooks/HookEnums.ts
src/processors/universal.ts

* filter order with specified allowedTaker 
Task: https://app.clickup.com/t/4717986/DEV-3672

fix: allowedTaker filter order

---

package-lock.json
package.json
src/processors/throughput.ts
tests/throughput.test.ts

This PR fixes #129 
Task ID: https://app.clickup.com/t/4717986/DEV-3439

fix: throughput must check upper bound range

---

package-lock.json
package.json
src/executors/executor.ts
src/processors/throughput.ts
tests/throughput.test.ts

This fixes a bug introduced by #129 and #133
Task ID: https://app.clickup.com/t/4717986/DEV-3732

fix: empty range must be preserved 

---

package-lock.json
package.json
src/executors/executor.ts
src/processors/swap-connector-implementation.service.ts
src/processors/universal.ts
src/providers/utils/tryInitAltSolana.ts

* update dln client
* use Jupiter v6 for solana swaps
Task: https://app.clickup.com/t/8692wrjgv

feature: new client

---

package-lock.json
package.json
src/processors/universal.ts

fix: round of gas to evm tx

---

package-lock.json
package.json
src/processors/swap-connector-implementation.service.ts

chore: bump version to 2.15.10
fix: set jup maxAccounts to 16

Reduce jup accounts to 16

---

package-lock.json
package.json
src/processors/universal.ts

This patch prints elapsed time taken for order processing
https://app.clickup.com/t/8692zr206

feat: track order processing time

---

package-lock.json
package.json
src/processors/universal.ts

This patch prints elapsed time taken for order processing that succeeded during fulfilment
https://app.clickup.com/t/8692zr206

add elapsed time tag for order fulfillment

---

package-lock.json
package.json
sample.config.ts
src/config.ts
src/executors/executor.ts
src/processors/swap-connector-implementation.service.ts

* jupiterConfig.maxAccounts in taker config 
Task: https://app.clickup.com/t/4717986/DEV-3921

feature: jupiterConfig with maxAccounts

---

package-lock.json
package.json

This fixes a bug when an order ([e.g.](https://app.debridge.finance/order?orderId=0xac7d55f1a18190db94c6e9e73795d8f8dee77927731623aba9b7daa1799d9c19))  is marked as non-profitable though it is exactly profitable
https://app.clickup.com/t/4717986/DEV-4038

update legacy profitability module to v2.2.2 to fix wrong decimals rounding with BN

---

package-lock.json
package.json
src/config.ts
src/executors/executor.ts
src/processors/swap-connector-implementation.service.ts

https://app.clickup.com/t/869379n1y

Allow Solana DEX blacklisting

---

package-lock.json
package.json
src/config.ts
src/processors/swap-connector-implementation.service.ts

This PR fixes #157 (https://github.com/debridge-finance/dln-taker/releases/tag/v2.17.1)

hotfix: update dln-ts-client so that reqs to Jupiter without excluded dex dont fail (#157)

---

package-lock.json
package.json
src/chain-evm/bumpedFeeManager.ts
src/chain-evm/order-estimator.ts
src/utils.ts

This PR fixes rounding issues when converting multiplied Numbers to BigInt
TaskID: https://app.clickup.com/t/8693akyew

fix: Number to BigInt conversion

---

package-lock.json
package.json
src/chain-common/order.ts

1:1 orders to Optimism do not pass pre-estimation with subsidy enabled
Task ID: https://app.clickup.com/t/8693cw7nv

Fix: respect subsidization on rough profitability pre-estimation

---

package-lock.json
package.json
src/executor.ts

https://app.clickup.com/t/8693ddcbg

fix: unlock authority has been messed up with fulfill authority

---

package-lock.json
package.json
sample.config.ts
src/configurator/tokenPriceService.ts

Task: https://app.clickup.com/t/8693dh1ar

feat: custom coingecko remapping

---

README.md
package-lock.json
package.json
sample.config.ts
sample.env
src/config.ts
src/environments.ts
src/executor.ts
src/processors/swap-connector-implementation.service.ts

- https://app.clickup.com/t/8693t3889 switch to 1inch v5
- https://app.clickup.com/t/4717986/DEV-3675 taker will now use `0x663DC15D3C1aC63ff12E45Ab68FeA3F0a883C251` as a principal `CrosschainForwarder`

feat: use Oneinch v5 and common CrosschainForwarder
